services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - n8n-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:rw

  n8n:
    image: n8nio/n8n:2.2.5
    container_name: n8n-main
    networks:
      - n8n-net
    environment:
      - GENERIC_TIMEZONE=Asia/Shanghai
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_BROKER_PORT=5679
      - N8N_RUNNERS_AUTH_TOKEN=your-secret-here
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_RUNNERS_TASK_TIMEOUT=7200
      - N8N_LOG_LEVEL=debug
      # - N8N_LOG_OUTPUT=console
      # - N8N_RUNNERS_TASK_REQUEST_TIMEOUT=120
    ports:
      - "5678:5678"
    volumes:
      - ./.n8n:/home/node/.n8n

  task-runners:
    build: ./runners
    # image: n8nio/runners:2.2.5
    container_name: n8n-runners
    networks:
      - n8n-net
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
      - N8N_RUNNERS_AUTH_TOKEN=your-secret-here
      - N8N_RUNNERS_TASK_TIMEOUT=7200
      - N8N_RUNNERS_LAUNCHER_LOG_LEVEL=debug
      - N8N_RUNNERS_STDLIB_ALLOW=*
      - N8N_RUNNERS_EXTERNAL_ALLOW=*
    depends_on:
      - n8n
    volumes:
      - videos_data:/home/runner/downloads:rw
      - ./cookies:/home/runner/cookies:rw

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - n8n-net
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - videos_data:/var/www/html/videos:ro

  # 辅助服务：专门用来初始化卷权限
  init-permissions:
    image: alpine
    networks:
      - n8n-net
    volumes:
      - videos_data:/mnt/downloads
      - ./cookies:/mnt/cookies
    command: chmod -R 777 /mnt/downloads /mnt/cookies # 赋予所有人读写执行权限

volumes:
  videos_data:
  redis_data:

networks:
  n8n-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24